---
version: "2.1"

services:
  autotranslate:
    image: zorbatherainy/autotranslate
    container_name: autotranslate
    environment:
      - DEEPL_AUTH_KEY=aaa11111-a1aa-1a11-a1a1-a1a1aa11aaa1:aa              # (mandatory) get your key at https://www.deepl.com/account/summary
      # - DEEPL_TARGET_LANG=EN-US                                           # (near mandatory)  The language isn't really changeable on the fly.  Assumes you want all your files translated to a common language
      # - DEEPL_USAGE_RENEWAL_DAY=1                                         # (optional) If you put the day of the month your DeepL allowance resets, then the expired usage sleeping will be more accurate.  Otherwise, it just waits 7 days before trying again.
      # - CHECK_EVERY_X_MINUTES=15                                          # (optional) How often you want the inputDir scanned for new files
      # - ORIGINAL_BEFORE_TRANSLATION=0                                     # (optional) Should the original be prepended or appended to the translated PDF?
      # - TRANSLATE_FILENAME=1                                              # (optional) Should the filename of the PDF be translated?
      # - USE_WEB_SERVER=1                                                  # (optional) Should the web server be run?
			# - NOTIFY_URLS='mailtos://example.com:12522?user=user1@example.com&pass=pass123&smtp=mail.example.com&from=joe@example.com&to=bob@example.com'
                                                                            # (optional) Apprise-style comma separated list of URLs to notify when errors or the final translation occurs.
    volumes:
      - /etc/localtime:/etc/localtime:ro                                    # (optional) sync to host time
      - /volume1/translate/:/inputDir                                       # (mandatory) The directory where you put the un-translated file
      - /volume1/consume/:/outputDir                                        # (mandatory) The directory where AutoTranslate will put the translated file
      - /volume1/translate/autotranslate_logs/:/logDir                      # (near mandatory) The directory where log files are stored, 1 per input file and a master log file
    ports:
      - '8881:8010'                                                         # (optional) Web server port mapping
